[package]
name = "skip_intro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[[bin]]
name="skip_intro"
path="src/main.rs"
edition="2021"